### ISSUE TITLE
Automate Prettier write format

### ISSUE THREAD

**Issue by geromegrignon** [scullyio/scully#1336]
### Description

Prettier is included into the project but not automated.
It makes the format of the soruce code inconsistent with each new contribution.
Furthermore, it slows down reviews on PRs with new formatbeing applied (in #1326 for example)

### Describe the solution you'd like

I would suggest to : 
- add a git hook
- include a format step into the CI (to protect the source code if a git hook is desactivated)

I can contribute to it.

**Comment by AlexScigalszky** [comment]
We can add new step in `.github/workflows/pull_request.yml`  with a prittier check like this:
``` yaml
- name: Check Code Format
   run: |
     npx prettier --check  ./scully/libs/scully/src/
```

What do you think about this?
