### ISSUE TITLE
[Gitlab CI] Scully rendering never ends

### ISSUE THREAD

**Issue by BenLune** [scullyio/scully#1403]
## 🐞 Bug report

Angular version : 12
Scully version : 1.1.1

### Description
Dear Scully Team,
Thanks again for Scully !
I have a strange thing (to me) I'd like to share with you.

When I run Scully locally, I have this behaviour : Generating took 2.88 seconds for 8 pages:
And then server stops like this : ✨  Done in 126.99s.
Here I don't understand why we have such a delay between the duration of the rendering and the end of the process.

My biggest problem is that, when I render Scully on GitLab Pipeline, Scully Job never ends. Do you know why ? Am I missing something ?

The pipeline log seems to be ok : 
```
Launching puppeteer with executablePath /usr/bin/chromium-browser
Route "/" rendered into file: "./dist/static/index.html"
Route "/photos/2" rendered into file: "./dist/static/photos/2/index.html"
Route "/photos/4" rendered into file: "./dist/static/photos/4/index.html"
Route "/photos" rendered into file: "./dist/static/photos/index.html"
Route "/photos/0" rendered into file: "./dist/static/photos/0/index.html"
Route "/photos/3" rendered into file: "./dist/static/photos/3/index.html"
Route "/photos/5" rendered into file: "./dist/static/photos/5/index.html"
Route "/photos/1" rendered into file: "./dist/static/photos/1/index.html"
Generating took 6.25 seconds for 8 pages:
  That is 1.28 pages per second,
  or 783 milliseconds for each page.
  
  Finding routes in the angular app took 1.71 seconds
  Pulling in route-data took 0 milliseconds
  Rendering the pages took 3.87 seconds
```
But the job never ends

Here is my Scully Config : 
```
import {HandledRoute, ScullyConfig} from '@scullyio/scully';

const { registerPlugin } = require('@scullyio/scully');

function photoIdPlugin(route: string, config = {}): Promise<HandledRoute[]> {
  return Promise.resolve([
    { route: '/photos/0' },
    { route: '/photos/1' },
    { route: '/photos/2' },
    { route: '/photos/3' },
    { route: '/photos/4' },
    { route: '/photos/5' }
  ]);
}

const validator = async () => [];
registerPlugin('router', 'photoIds', photoIdPlugin, validator);

export const config: ScullyConfig = {
  projectRoot: "./src",
  puppeteerLaunchOptions: {
    args: ['--no-sandbox', '--disable-setuid-sandbox']
  },
  projectName: "ngx-ng12-tailwind-poc",
  outDir: './dist/static',
  routes: {
    '/photos/:id': {
      type: 'photoIds',
    }
  }
};
```

Here is my Gitlab Pipeline : 
```
scully:
  stage: scully
  image: node:12-alpine
  tags:
    - docker
  before_script:
    - apk add chromium
    - export SCULLY_PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
  script:
    - yarn install
    - yarn ngcc --properties es2015 --create-ivy-entry-points
    - yarn build
    - yarn scully
  after_script:
    - cp $PROJECT_PATH/Dockerfile $APP_OUTPUT_PATH
  artifacts:
    name: "ngx-ng12-tailwind-poc"
    paths:
      - $APP_OUTPUT_PATH
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
    policy: pull
```
