### ISSUE TITLE
showGuessError return nothing in GitHub Action

### ISSUE THREAD

**Issue by phodal** [scullyio/scully#448]
### Description

I run `npx scully` can success build in my local env. but when run in GitHub ci, it failure, add return nothing.

here is my build: https://github.com/phodal/ledge/runs/570186601?check_suite_focus=true

and my config: https://github.com/phodal/ledge/blob/master/scully.ledge.config.js

#### 💻Your Environment

**Angular Version:** 9.0.4

**Scully Version:** latest

## 🔥 Exception or Error

```bash
Run npx scully --showGuessError
  npx scully --showGuessError
  shell: /bin/bash -e {0}
 ☺   new Angular build imported
 ☺   Started servers in background
Could not connect to server
##[error]Process completed with exit code 15.
```

**Comment by phodal** [comment]
I change config to this, and it works.

```yml
      - name: Build Scully
        run: |
          npx scully --showGuessError
        continue-on-error: true
```
