### ISSUE TITLE
Scully Doesn't work with Github Actions

### ISSUE THREAD

**Issue by vistaar-dgada** [scullyio/scully#451]
### Description
There's some issue with scully, it doesn't build up while running inside github actions.

#### 🔬 Minimal Reproduction
.github/workflows/build.yml
```
name: Angular Build Test

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build:prod --if-present

      - name: Scully
        run: npm run scully -- --nw
```

#### 💻Your Environment

**Angular Version:**
<pre>
9.1.0
</pre>

**Scully Version:**
<pre>
6.13.4
</pre>

## 🔥 Exception or Error

<pre>
> ***@5.0.0 scully /home/runner/work/***/***
> scully "--nw"

No routes defined in ""
 ☺   new Angular build imported
 ☺   Started servers in background
Could not connect to server
npm ERR! code ELIFECYCLE
npm ERR! errno 15
npm ERR! ***@5.0.0 scully: `scully "--nw"`
npm ERR! Exit status 15
npm ERR! 
npm ERR! Failed at the ***@5.0.0 scully script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-04-09T09_27_52_371Z-debug.log
##[error]Process completed with exit code 15.
</pre>

## 🔥 Screenshot
<img width="1436" alt="Screenshot 2020-04-09 at 3 28 35 PM" src="https://user-images.githubusercontent.com/46889415/78883789-98b64380-7a77-11ea-8ac2-71a369fe5d4f.png">
