### ISSUE TITLE
Scully Doesn't work with Github Actions {Tried with --host as well} 

### ISSUE THREAD

**Issue by dr5hn** [scullyio/scully#461]
### Description
There's some issue with scully, it doesn't build up while running inside github actions.

#### 🔬 Minimal Reproduction
.github/workflows/build.yml
```
name: Angular Build Test

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build:prod --if-present

      - name: Scully
        run: npm run scully -- --host='0.0.0.0'
```

#### 💻Your Environment

**Angular Version:**
<pre>9.1.0</pre>

**Scully Version:**
<pre>6.13.4</pre>

## 🔥 Exception or Error
<pre>> ***@5.0.0 scully /home/runner/work/***/***
> scully "--host=0.0.0.0"

 ☺   new Angular build imported
 ☺   Started servers in background
Could not connect to server
npm ERR! code ELIFECYCLE
npm ERR! errno 15
npm ERR! ***@5.0.0 scully: `scully "--host=0.0.0.0"`
npm ERR! Exit status 15
npm ERR! 
npm ERR! Failed at the ***@5.0.0 scully script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-04-13T06_08_54_188Z-debug.log
##[error]Process completed with exit code 15.</pre>

## 🔥 Screenshots
<img width="1440" alt="Screenshot 2020-04-13 at 12 02 31 PM" src="https://user-images.githubusercontent.com/6929121/79098014-b0930d80-7d7e-11ea-9731-10c8d07bedfa.png">
